export const TIME_LIMIT_HARD_CUTOFF_SECONDS = 1800;
export const TIME_LIMIT_SOFT_WARNING_SECONDS = 1500;
export const TIME_LIMIT_MINIMUM_SECONDS = 900;

export const SHARED_CONFIG = {
  TIME_LIMIT_HARD_CUTOFF_SECONDS,
  TIME_LIMIT_SOFT_WARNING_SECONDS,
  TIME_LIMIT_MINIMUM_SECONDS,
};
